backend:
  name: git-gateway
  branch: main

# Это заставит админку обновляться сразу
local_backend: false 

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Контент сайта"
    delete: false # Нельзя удалять главную
    editor:
      preview: false # Отключаем превью, чтобы не глючило
    files:
      - file: "data/home.json"
        label: "Главная страница"
        name: "home_page"
        fields:
          - { label: "Верхнее слово (Moto)", name: "h1_span", widget: "string" }
          - { label: "Нижнее слово (Fest)", name: "h1_main", widget: "string" }
          - { label: "Описание текста", name: "description", widget: "text" }
          - { label: "Дата проведения", name: "event_date", widget: "string" }
          - { label: "Афиша (Загрузить фото)", name: "afisha", widget: "image" }
